name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/github-script@v6
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        with:
          script: |
            console.log(${process.env.TMDB_API_KEY})
            git config --global user.name "TharuneshwarV"
            git config --global user.email "tharuneshwarv@gmail.com"
            git checkout gh-pages
            git rm -rf .
            cp -r build/. .
            git add .
            git commit -m "Deploy React app"
            git push origin gh-pages
